version: 2.1

orbs:
  ruby: circleci/ruby@0.1.2
  heroku: circleci/heroku@0.0.10

workflows:
  heroku_deploy:
    jobs:
      - build
      # TODO: uncomment job job post-stack upgrade
      # - heroku/deploy-via-git:
      #     requires:
      #       - build
      #     filters:
      #       branches:
      #         only: main
      #     post-steps:
      #       - run: heroku run rails db:migrate --app spotme-app

jobs:
  build:
    parallelism: 1
    docker:
      - image: cimg/ruby:3.1.4
      - image: cimg/postgres:13.9
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: spot_me_frontend_test
    environment:
      # Bundler config to match local
      BUNDLE_PATH: vendor/bundle
      BUNDLE_JOBS: 3
      BUNDLE_RETRY: 3
      PGHOST: 127.0.0.1
      PGUSER: postgres
      RAILS_ENV: test
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - run:
          name: Ensure Bundler 2.3.25 (matches lockfile)
          command: gem install bundler -v 2.3.25
      - ruby/bundle-install
      - run:
          name: Install Node + Yarn (for Rails 6 assets)
          command: |
            sudo apt-get update
            sudo apt-get install -y nodejs yarn
      - run:
          name: Setup Test DB
          command: bundle exec rails db:create db:schema:load --trace
      - run:
          name: Run Test Suite
          command: bundle exec rspec -fd
