development:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: spot_me_frontend_development
  username: postgres
  host: 127.0.0.1

test:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: spot_me_frontend_test
  username: postgres
  host: 127.0.0.1

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: spot_me_frontend_production
  username: spot_me_frontend
  password: <%= ENV['SPOT_ME_FRONTEND_DATABASE_PASSWORD'] %>
